name: DockerYML
on: [push]

#on: 
#  Schedule:
#  - cron: "4 "

#on: 
#  self-hosted

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: blazemeter/taurus:latest
    steps:
      - uses: actions/checkout@v2
      - name: Run TaurusJmeter Test
        run: |
          pwd
          bzt CompetitorsByDriveTimeControllerApi.yaml
          echo "LoadTest Started"
          
      - name: Upload Results
      - uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl

